#!/bin/bash -xe

# STEP 1 - Updates
sudo yum -y update
    
# STEP 2 - Install Nginx
sudo yum install -y nginx

# STEP 3 - Start Nginx
sudo systemctl enable nginx
sudo systemctl start nginx

# STEP 4 - Custom Random Web Page
bgcolor=$(printf "%02x%02x%02x\n" $((RANDOM%256)) $((RANDOM%256)) $((RANDOM%256)))
TOKEN=$(curl -X PUT "http://169.254.169.254/latest/api/token" -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")
instanceId=$(curl -H "X-aws-ec2-metadata-token: $TOKEN" http://169.254.169.254/latest/meta-data/instance-id)
sudo wget -O /usr/share/nginx/html/cat.gif "http://thecatapi.com/api/images/get?format=src&type=gif&api_key=8f7dc437-0b9b-47b8-a2c0-65925d593acf"
echo "<html><head>" | sudo tee /usr/share/nginx/html/index.html
echo "<meta http-equiv=\"Cache-Control\" content=\"no-cache, no-store, must-revalidate\">" | sudo tee -a /usr/share/nginx/html/index.html
echo "<meta http-equiv=\"Pragma\" content=\"no-cache\">" | sudo tee -a /usr/share/nginx/html/index.html
echo "<meta http-equiv=\"Expires\" content=\"0\">" | sudo tee -a /usr/share/nginx/html/index.html
echo "</head><body style=\"background-color:#$bgcolor;\">" | sudo tee -a /usr/share/nginx/html/index.html
echo "<center><h1>Instance ID : $instanceId</h1></center><br>" | sudo tee -a /usr/share/nginx/html/index.html
echo "<center><img src=\"cat.gif?nocache=<?php echo time(); ?>\">" | sudo tee -a /usr/share/nginx/html/index.html
echo "</body></html>" | sudo tee -a /usr/share/nginx/html/index.html

# STEP 5 - Set Permissions
sudo chmod -R 755 /usr/share/nginx/html

# STEP 6 - Restart Nginx
sudo systemctl restart nginx
